# -*- coding: utf-8 -*-
"""diccionario  alumnos-menu githut

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yd_9AEBzAvKolErr-o_KoLkC6xz6cpo8
"""

contacto ={
        "nombre":input("ingrese nombre"),
        "telefono":int(input("ingrese numero de telefono")) ,
        "email":input("ingrese su gmail"),
        "edad":input("ingrese su edaa")
  }

while True:

      print("----------------menu de opciones---------")
      print("1 ver ficha")
      print("2 editar dato")
      print("3 salir")
      opc= int(input("ingrese una opcion"))
      if opc ==1 :


       print("-----------ficha de contacto------------")
       print(f"su nombre es :{contacto["nombre"]}")
       print(f"su edad es {contacto["telefono"]}")
       print(f"su gmail es{contacto["email"]}")
       print(f"su edad es{contacto["edad"]}")

      elif opc ==2:
        campo=input("que campo desea editar(nombre, telefono,  email,  edad)")
        nuevovalor=input("ingrese nuevo valor")
        if campo == "nombre":
          contacto ["nombre"] = nuevovalor

        elif campo == "telefono":
          contacto ["telefono"] = int(nuevovalor)

        elif campo == "":
          contacto ["email"] = nuevovalor

        elif campo == "edad":
         contacto ["edad"] = int(nuevovalor)

         print("-----------ficha actualizada------------")
         print(f"su nombre es :{contacto["nombre"]}")
         print(f"su edad es {contacto["telefono"]}")
         print(f"su gmail es{contacto["email"]}")
         print(f"su edad es{contacto["edad"]}")

      if opc == 3:
        print("terminando el programa")
        break

alumno={
    "nombre":input("ingrese nombre"),
    "edad":int(input("ingrese edad")),
    "correo":input("ingrese correo"),
    "telefono":input("ingrese el telefono")




}

while True:

      print("----------------menu de opciones---------")
      print("1 ver ficha")
      print("2 editar dato")
      print("3 salir")
      opc= int(input("ingrese una opcion"))
      if opc ==1 :
        print(alumno)
      elif opc ==2:
        campo=input("que campo desea modificar")
        nuevo=input("ingrese el nuevo dato")
        alumno[campo]= nuevo
      elif opc ==3:
        print("saliendo")

        break
      print(alumno)