# -*- coding: utf-8 -*-
"""ejercico listas de phython

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SQIN2ANjjbOHdbF30srxF7xC1zWeq183
"""

#funciones phython
#ultima materia
# para usar una fuincion usamos def nombre():
        #                        instrucciones
        #                       nombre_funcion    llamarla
#sin argumentos sin retorno
def saludar_alumno():
   print("hola alumnos, bienvenido al curso")
saludar_alumno()
saludar_alumno()
saludar_alumno()
#primer tipo sin argumento y sin retorno   tipo 1°

#tipo 2°   sin argumento pero con retorno
def obtener_año_actual():
  año=2026
  nombre="jorge"
  edad= 28
  return   nombre   #aca elijo lo que quiero que retorne
print(obtener_año_actual())

nombre=input("ingrese un nombre")
nota=float(input("ingrese nota"))

def mostrar_estado(nombre, nota):
    if nota >= 4.0 :

       estado ="aprobo el ramo"

    else:
         estado ="reprobo el ramo"

    print(f"nombre {nombre}")
    print(f"estado {estado}")


mostrar_estado(nombre, nota)

def calcular_promedio(notas):
  total =sum(notas)
  prom = total /len(notas)
  return round(prom, 1)
#el resultado lo guarda y usas

notas_ana = [6.5, 5.8, 7.0 ]
prom_ana = calcular_promedio(notas_ana)
print(f"promedio { prom_ana}")

#1°
def saludar():
   print("-------menu--------")
   print("1 °c-> °f")
   print("2 °f -> °c")
   print("salir")
saludar()

def pedir_ususario():#2°
  temperatura=float(input("ingrese temperatura"))

  return   temperatura
print(pedir_ususario())

def mostrar_estado(orig, conv, ud):#con argumentos sin retorno 3°
    print(orig)
    print(conv)
    print(ud)
mostrar_estado(3.0, 40, "cf")

#4°
c= float(input("ingrese los grados"))
def cel_a_fa(c):
  return (c* 9/5) +32
cel_a_fa(c)

f=float(input("ingrese los grados"))
def fa_a_c(f):
  return (f  -32 ) *5/9
fa_a_c(f)