# -*- coding: utf-8 -*-
"""estudiar prueba 4 phython

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yb_O6pgZPRkGm5jeuYxhUYWOf4Mm-Gj6
"""

#preparacion de la prueba 4, que viene  (lista de tareas, diicionarios , funciones separadas,  validaciones ,   menu con while,   buscar y eliminar)
#hoy veremos lista .append(x)  agrega x al final

#lista
tareas= ["estudiar phython", "hacer ejercio", "leer" ]
print("primer elemento: ",tareas[0])
print("segundo elemento: ",tareas[1])
print("tercer elemento: ",tareas[2])

print("-----------------------------------")

tareas.append("traer chocolates al profe")#agregar un elemento ala lista

print(tareas)
print("---------------")
print("la cantida de tareas que tenemos", len(tareas))
#contar tareas
print("_-------------------------------------")
eliminado = tareas.pop(0)#borrar o eliminar un elemento dentro de la lista
print("la tarea borrada es", eliminado)
print(tareas)
print("------------------------------------")
for i in tareas:
   print(i)
   print("---------------------------------")
for i,tareas in enumerate(tareas):#mas ordenado for con indice
  print(i, "-", tareas)


#estudiar y recordar

fruta=[]
fruta.append("pera")
fruta.append("manzana")
fruta.append("uva")

print("la segunda fruta es",fruta[1])
eliminado = fruta.pop(0)
print("el elemento eliminado es", eliminado)
print("la lista actualizada es :" ,fruta)
print(len(fruta))

#empezamos con los diccionarios
tarea={"descripcion":"estudiar phython",
       "prioridad" : 10,
       "tiempo estipado":2.5,
       "completada" : False

}
#print(tarea)

tarea["descripcion"]#accede a un campo del diccionario
#modificar un campo del diccionario
tarea["completada"] = True

#agregar un campo nuevo
tarea["nota"] = "urgente"

print(tarea)

#crea a mano un diccionario llamado tarea 1 con los 4campos luefo imprime cada campo por separado
tarea1={"descripcion":"hacer informe",
       "prioridad":7,
        "tiempoestimado:": 2.5,
       "completada": False
}
print(tarea["descripcion"])
print(tarea["prioridad"])

print(tarea["completada"])

#funcion
def llamar_nombre():
  nombre = input("ingrese su nombre")
  return nombre
llamar_nombre()

#estudiar fuincion muy importante
def validar_prioridad (p):
    return 1 <= p <= 10

def agregar_tarea(lista):
    desc = input("descripcion")
    prio= int(input("prioridad (1-10):"))
    if validar_prioridad(prio):
        tarea ={
            "descripcion": desc,
            "prioridad": prio,
            "completado": False

        }
        lista.append(tarea)
        print("tarea agregada")
    else:
      print("prioridad invalida")


mis_tareas = []
agregar_tarea(mis_tareas)
print(mis_tareas)