# -*- coding: utf-8 -*-
"""prueba ultima

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QQNmjZu9yp_Nsrqls1Hb1WEsT9vxXicM
"""

juegos = {
    'G001': ['Eclipse Runner', 'PC', 'accion', 'T', True,  'NovaStudio'],
    'G002': ['Puzzle Atlas',   'Switch','puzzle','E', False, 'BrightWorks'],
    'G003': ['Sky Legends',    'PS5',  'aventura','T',True,  'OrionGames'],
    'G004': ['Racing Pulse',   'PC',   'carreras','E',True,  'VelocityLab'],
    'G005': ['Mystic Farm',    'Switch','simulacion','E',False,'GreenSeed'],
    'G006': ['Shadow Tactics', 'Xbox', 'estrategia','M',False,'IronGate'],
}

inventario = {
    'G001': [9990,  7],
    'G002': [19990, 0],
    'G003': [42990, 3],
    'G004': [14990, 5],
    'G005': [17990, 9],
    'G006': [39990, 2],
}


def mostrar_menu():
    print("\n========== MENU PRINCIPAL ==========")
    print("1. Stock por plataforma")
    print("2. Busqueda de juegos por rango de precio")
    print("3. Actualizar precio de juego")
    print("4. Agregar juego")
    print("5. Eliminar juego")
    print("6. Salir")
    print("=====================================")

def leer_opcion():
      while True:
        try:
          op = int(input("ingrese una opcion"))
          if 1 <= op <= 6:
            return op
          print("debe seleccionar una opcion")
        except:
          print("debe ingresar opcion valida")
def stock_plataforma(plataforma, juegos , inventario):
  total = 0
  for codigo , datos in juegos.items():
    if datos [1].upper() == plataforma.upper():
     total =inventario[codigo][1]
  print(f"el inventario disponible es {total}")


def busqueda_precio(p_min, p_max, juegos, inventario):
    resultado = []
    for codigo, datos in inventario.items():
        precio = datos[0]
        stock  = datos[1]
        if p_min <= precio <= p_max and stock > 0:
            titulo = juegos[codigo][0]
            resultado.append(f"{titulo}--{codigo}")

    if len(resultado) == 0:
        print("No hay juegos en ese rango de precios.")
    else:
        resultado.sort()
        print(f"Los juegos encontrados son: {resultado}")

def buscar_codigo(codigo, juegos):
    return codigo.upper() in juegos

def actualizar_precio(codigo, nuevo_precio, juegos, inventario):
    if buscar_codigo(codigo, juegos):
        inventario[codigo.upper()][0] = nuevo_precio
        return True
    return False

def eliminar_juego(codigo, juegos, inventario):
    if buscar_codigo(codigo, juegos):
        del juegos[codigo.upper()]
        del inventario[codigo.upper()]
        return True
    return False

def agregar_juego(codigo, titulo, plataforma, genero, clasificacion, multiplayer, editor, precio, stock, juegos, inventario):
    if codigo.upper() in juegos:
        return False
    multi = True if multiplayer == 's' else False
    juegos[codigo.upper()] = [titulo, plataforma, genero, clasificacion, multi, editor]
    inventario[codigo.upper()] = [int(precio), int(stock)]
    return True

def val_texto(dato):
    return len(dato.strip()) > 0

def val_clasificacion(dato):
    return dato in ['E', 'T', 'M']

def val_multiplayer(dato):
    return dato in ['s', 'n']

def val_precio(dato):
    try:
        return int(dato) > 0
    except:
        return False

def val_stock(dato):
    try:
        return int(dato) >= 0
    except:
        return False

def val_codigo_nuevo(codigo, juegos):
    return len(codigo.strip()) > 0 and codigo.upper() not in juegos

while True:
    mostrar_menu()
    opcion = leer_opcion()
    if opcion == 1:
        plataforma = input("Ingrese plataforma a consultar: ")
        stock_plataforma(plataforma, juegos, inventario)

    elif opcion == 2:
        while True:
            try:
                p_min = int(input("Ingrese precio minimo: "))
                p_max = int(input("Ingrese precio maximo: "))
                break
            except ValueError:
                print("Debe ingresar valores enteros")
        busqueda_precio(p_min, p_max, juegos, inventario)

    elif opcion == 3:
        while True:
            codigo = input("Ingrese codigo del juego: ")
            nuevo_precio = input("Ingrese nuevo precio: ")
            try:
                nuevo_precio = int(nuevo_precio)
                if nuevo_precio > 0:
                    break
                print("El precio debe ser mayor que cero")
            except ValueError:
                print("Debe ingresar un entero")

        resultado = actualizar_precio(codigo, nuevo_precio, juegos, inventario)
        if resultado:
            print("Precio actualizado")
        else:
            print("El codigo no existe")

        resp = input("Desea actualizar otro precio (s/n)?: ")
        if resp.lower() != 's':
            pass  # Regresa al menú
    elif opcion == 4:
        codigo     = input("Ingrese codigo: ")
        titulo     = input("Ingrese titulo: ")
        plataforma = input("Ingrese plataforma: ")
        genero     = input("Ingrese genero: ")
        clasif     = input("Ingrese clasificacion (E/T/M): ")
        multi      = input("Es multiplayer? (s/n): ")
        editor     = input("Ingrese editor: ")
        precio     = input("Ingrese precio: ")
        stock      = input("Ingrese stock: ")

        # Validaciones en cascada
        if not val_codigo_nuevo(codigo, juegos):
            print("Codigo invalido o ya existe")
        elif not val_texto(titulo):
            print("Titulo invalido")
        elif not val_texto(plataforma):
            print("Plataforma invalida")
        elif not val_texto(genero):
            print("Genero invalido")
        elif not val_clasificacion(clasif):
            print("Clasificacion invalida (Debe ser E, T o M)")
        elif not val_multiplayer(multi):
            print("Multiplayer invalido (Debe ser s o n)")
        elif not val_texto(editor):
            print("Editor invalido")
        elif not val_precio(precio):
            print("Precio invalido")
        elif not val_stock(stock):
            print("Stock invalido")
        else:
            ok = agregar_juego(codigo, titulo, plataforma, genero, clasif, multi, editor, precio, stock, juegos, inventario)
            print("Juego agregado" if ok else "El codigo ya existe")

    # Opción 5: Eliminar juego
    elif opcion == 5:
        codigo = input("Ingrese codigo del juego a eliminar: ")
        resultado = eliminar_juego(codigo, juegos, inventario)
        if resultado:
            print("Juego eliminado exitosamente.")
        else:
            print("El codigo no existe.")

    # Opción 6: Salir
    elif opcion == 6:
        print("Programa finalizado.")
        break

# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jUJy2A6S66SM44ouiYOssJ4d8ULZgDVf
"""

# ==========================================
# 1. DICCIONARIOS DE DATOS
# ==========================================
juegos = {
    'G001': ['Eclipse Runner', 'PC', 'accion', 'T', True,  'NovaStudio'],
    'G002': ['Puzzle Atlas',   'Switch','puzzle','E', False, 'BrightWorks'],
    'G003': ['Sky Legends',    'PS5',  'aventura','T',True,  'OrionGames'],
    'G004': ['Racing Pulse',   'PC',   'carreras','E',True,  'VelocityLab'],
    'G005': ['Mystic Farm',    'Switch','simulacion','E',False,'GreenSeed'],
    'G006': ['Shadow Tactics', 'Xbox', 'estrategia','M',False,'IronGate'],
}

inventario = {
    'G001': [9990,  7],
    'G002': [19990, 0],
    'G003': [42990, 3],
    'G004': [14990, 5],
    'G005': [17990, 9],
    'G006': [39990, 2],
}

# ==========================================
# 2. FUNCIONES DEL MENÚ Y REPORTES (OPCIONES 1 Y 2)
# ==========================================
def mostrar_menu():
    print("\n========== MENU PRINCIPAL ==========")
    print("1. Stock por plataforma")
    print("2. Busqueda de juegos por rango de precio")
    print("3. Actualizar precio de juego")
    print("4. Agregar juego")
    print("5. Eliminar juego")
    print("6. Salir")
    print("=====================================")

def leer_opcion():
    while True:
        try:
            op = int(input("Ingrese opcion: "))
            if 1 <= op <= 6:
                return op
            print("Debe seleccionar una opcion valida")
        except ValueError:
            print("Debe seleccionar una opcion valida")

def stock_plataforma(plataforma, juegos, inventario):
    total = 0
    for codigo, datos in juegos.items():
        if datos[1].upper() == plataforma.upper():
            total += inventario[codigo][1]
    print(f"El total de stock disponibles es: {total}")

def busqueda_precio(p_min, p_max, juegos, inventario):
    resultado = []
    for codigo, datos in inventario.items():
        precio = datos[0]
        stock  = datos[1]
        if p_min <= precio <= p_max and stock > 0:
            titulo = juegos[codigo][0]
            resultado.append(f"{titulo}--{codigo}")

    if len(resultado) == 0:
        print("No hay juegos en ese rango de precios.")
    else:
        resultado.sort()
        print(f"Los juegos encontrados son: {resultado}")

# ==========================================
# 3. FUNCIONES DE ACTUALIZACIÓN Y ELIMINACIÓN (OPCIONES 3 Y 5)
# ==========================================
def buscar_codigo(codigo, juegos):
    return codigo.upper() in juegos

def actualizar_precio(codigo, nuevo_precio, juegos, inventario):
    if buscar_codigo(codigo, juegos):
        inventario[codigo.upper()][0] = nuevo_precio
        return True
    return False

def eliminar_juego(codigo, juegos, inventario):
    if buscar_codigo(codigo, juegos):
        del juegos[codigo.upper()]
        del inventario[codigo.upper()]
        return True
    return False

# ==========================================
# 4. FUNCIONES DE VALIDACIÓN Y AGREGAR (OPCIÓN 4)
# ==========================================
def val_texto(dato):
    return len(dato.strip()) > 0

def val_clasificacion(dato):
    return dato.upper() in ['E', 'T', 'M']

def val_multiplayer(dato):
    return dato.lower() in ['s', 'n']

def val_precio(dato):
    try:
        return int(dato) > 0
    except ValueError:
        return False

def val_stock(dato):
    try:
        return int(dato) >= 0
    except ValueError:
        return False

def val_codigo_nuevo(codigo, juegos):
    return len(codigo.strip()) > 0 and codigo.upper() not in juegos

def agregar_juego(codigo, titulo, plataforma, genero, clasificacion, multiplayer, editor, precio, stock, juegos, inventario):
    if codigo.upper() in juegos:
        return False
    multi = True if multiplayer.lower() == 's' else False
    juegos[codigo.upper()] = [titulo, plataforma, genero, clasificacion.upper(), multi, editor]
    inventario[codigo.upper()] = [int(precio), int(stock)]
    return True

# ==========================================
# 5. PROGRAMA PRINCIPAL (LOOP)
# ==========================================
while True:
    mostrar_menu()
    opcion = leer_opcion()

    if opcion == 1:
        plataforma = input("Ingrese plataforma a consultar: ")
        stock_plataforma(plataforma, juegos, inventario)

    elif opcion == 2:
        while True:
            try:
                p_min = int(input("Ingrese precio minimo: "))
                p_max = int(input("Ingrese precio maximo: "))
                break
            except ValueError:
                print("Debe ingresar valores enteros")
        busqueda_precio(p_min, p_max, juegos, inventario)

    elif opcion == 3:
        while True:
            codigo = input("Ingrese codigo del juego: ")
            nuevo_precio = input("Ingrese nuevo precio: ")
            try:
                nuevo_precio = int(nuevo_precio)
                if nuevo_precio > 0:
                    break
                print("El precio debe ser mayor que cero")
            except ValueError:
                print("Debe ingresar un entero")

        resultado = actualizar_precio(codigo, nuevo_precio, juegos, inventario)
        if resultado:
            print("Precio actualizado")
        else:
            print("El codigo no existe")

        resp = input("Desea actualizar otro precio (s/n)?: ")
        if resp.lower() != 's':
            pass

    elif opcion == 4:
        codigo    = input("Ingrese codigo: ")
        titulo    = input("Ingrese titulo: ")
        plataforma= input("Ingrese plataforma: ")
        genero    = input("Ingrese genero: ")
        clasif    = input("Ingrese clasificacion (E/T/M): ")
        multi     = input("Es multiplayer? (s/n): ")
        editor    = input("Ingrese editor: ")
        precio    = input("Ingrese precio: ")
        stock     = input("Ingrese stock: ")

        if not val_codigo_nuevo(codigo, juegos):
            print("Codigo invalido o ya existe")
        elif not val_texto(titulo):
            print("Titulo invalido")
        elif not val_texto(plataforma):
            print("Plataforma invalida")
        elif not val_texto(genero):
            print("Genero invalido")
        elif not val_clasificacion(clasif):
            print("Clasificacion invalida")
        elif not val_multiplayer(multi):
            print("Multiplayer invalido")
        elif not val_texto(editor):
            print("Editor invalido")
        elif not val_precio(precio):
            print("Precio invalido")
        elif not val_stock(stock):
            print("Stock invalido")
        else:
            ok = agregar_juego(codigo, titulo, plataforma, genero, clasif, multi, editor, precio, stock, juegos, inventario)
            print("Juego agregado" if ok else "El codigo ya existe")

    elif opcion == 5:
        codigo = input("Ingrese el codigo del juego a eliminar: ")
        if eliminar_juego(codigo, juegos, inventario):
            print("Juego eliminado exitosamente.")
        else:
            print("El codigo no existe.")

    elif opcion == 6:
        print("Programa finalizado.")
        break