# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysPr4BonE4rWsXIO82DZnDt9lMb7WPnY
"""

#funciones en phython

# try exept:

#%
#par o impar

numero = int(input("ingrese un numero"))
if numero % 2 == 0:
   print("este numero es par")
else:
  print("este numero es impar")

numero = int(input("ingrese un numero"))
def numero_par (numero):

 if numero % 2 == 0:
    print("este numero es par")
 else:
   print("este numero es impar")
numero_par(numero)

numero = int(input("ingrese un numero"))
def numero_par (numero):

 if numero % 2 == 0:
   return True

 else:
   return False
numero_par(numero)

#numero 2


def pedir_numero():

 while True:
  try:
    numero = int(input("ingrese un numero"))
    return numero



  except:
   print("error, debe ser un numero")
pedir_numero()

#numero 1
def es_par (numero)

 if numero % 2== 0:
    return True
 else:
    return False

#numero 3
def main() :
  numero = pedir_numero()
  if es_par(numero):
    print(f"el numero es par{ numero }es par")
  else:
    print("el numero no es par")
main()

def es_par (numero)

 if numero % 2== 0:
    return True
 else:
    return False

def pedir_numero():

 while True:
  try:
    numero = int(input("ingrese un numero"))
    return numero



  except:
   print("error, debe ser un numero")
pedir_numero()

def main() :
  numero = pedir_numero()
  if es_par(numero):
    print(f"el numero es par{ numero }es par")
  else:
    print("el numero no es par")
main()

def es_par(numero):
    if numero % 2 == 0:
        return True
    else:
        return False
def pedir_numero():
    while True:
        try:
            numero = int(input("Ingrese un número: "))
            return numero
        except ValueError:
            print("Error, debe ser un número entero.")
def main():
    numero = pedir_numero()
    if es_par(numero):
        print(f"El número {numero} es par.")
    else:
        print(f"El número {numero} es impar (no es par).")
main()

def numeropar(numero):
    if numero % 2 == 0:
       return True
    else:
       return False
def  pedir_numero():
     while True:
        try:
            numero = int(input("imgrese un numero"))
            return numero
        except :
          print("Error, debe ser un numero entero")
def main():
    numero = pedir_numero()
    if numeropar(numero):
       print(f"el numero {numero} es par")
    else:
       print(f"el numero { numero} es impar")
main()

def numeropar(numero):
    if numero % 2 == 0:
       return True
    else:
       return False
def pedir_numero():
    while True:
      try:
         numero = int(input("ingrese un numero"))
         return numero
      except :
          print("error, debe ser un numero entero")
def main():
    numero = pedir_numero()
    if numeropar(numero):
       print(f"el numero {numero} es par ")
    else:
       print(f"el numero {numero }es impar")
main()

def numeropar(numero):
  if numero % 2 == 0:
    return True
  else:
    return False
def ingresenumero():
    while True:
      try:
        numero= int(input("ingrese un numero"))
        return numero
      except :
        print("error, el numero debe ser un numero entero")
def main():
    numero = pedir_numero()
    if numeropar(numero):
       print(f"el numero {numero} es par")
    else:
        print(f"el numero{ numero}es impar")

def calcular_doble(numero):
    resultado = numero * 2
    return resultado  # Envía el resultado hacia afuera


# Ahora sí podemos guardar y reusar el valor
mi_numero = calcular_doble(5)  # mi_numero ahora vale 10
print(mi_numero + 5)